# Generated by Django 6.0.3 on 2026-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(default='no-image.jpg', max_length=150),
        ),
    ]
